(cl:defpackage r3liveGPU-msg
  (:use )
  (:export
   "<INT32_POINTCLOUD>"
   "INT32_POINTCLOUD"
   "<INT32_POINTCLOUD2>"
   "INT32_POINTCLOUD2"
   "<STAMPEDEULERCUR>"
   "STAMPEDEULERCUR"
   "<STAMPEDFLOAT64MULTIARRAY>"
   "STAMPEDFLOAT64MULTIARRAY"
   "<STAMPEDINT32>"
   "STAMPEDINT32"
   "<STAMPEDPOSEND>"
   "STAMPEDPOSEND"
   "<STAMPEDQUATERNION>"
   "STAMPEDQUATERNION"
   "<STATE>"
   "STATE"
  ))

