// Generated by gencpp from file r3liveGPU/StampedInt32.msg
// DO NOT EDIT!


#ifndef R3LIVEGPU_MESSAGE_STAMPEDINT32_H
#define R3LIVEGPU_MESSAGE_STAMPEDINT32_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Int32.h>

namespace r3liveGPU
{
template <class ContainerAllocator>
struct StampedInt32_
{
  typedef StampedInt32_<ContainerAllocator> Type;

  StampedInt32_()
    : header()
    , data()  {
    }
  StampedInt32_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::r3liveGPU::StampedInt32_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r3liveGPU::StampedInt32_<ContainerAllocator> const> ConstPtr;

}; // struct StampedInt32_

typedef ::r3liveGPU::StampedInt32_<std::allocator<void> > StampedInt32;

typedef boost::shared_ptr< ::r3liveGPU::StampedInt32 > StampedInt32Ptr;
typedef boost::shared_ptr< ::r3liveGPU::StampedInt32 const> StampedInt32ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r3liveGPU::StampedInt32_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r3liveGPU::StampedInt32_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::r3liveGPU::StampedInt32_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedInt32_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::r3liveGPU::StampedInt32_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedInt32_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace r3liveGPU

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedInt32_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedInt32_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedInt32_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9f390858a15eeec6932d08bb09b9fed";
  }

  static const char* value(const ::r3liveGPU::StampedInt32_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9f390858a15eeecULL;
  static const uint64_t static_value2 = 0x6932d08bb09b9fedULL;
};

template<class ContainerAllocator>
struct DataType< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r3liveGPU/StampedInt32";
  }

  static const char* value(const ::r3liveGPU::StampedInt32_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StampedInt32.msg\n"
"\n"
"std_msgs/Header header\n"
"std_msgs/Int32 data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
;
  }

  static const char* value(const ::r3liveGPU::StampedInt32_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StampedInt32_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r3liveGPU::StampedInt32_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r3liveGPU::StampedInt32_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R3LIVEGPU_MESSAGE_STAMPEDINT32_H
