// Generated by gencpp from file r3liveGPU/StampedQuaternion.msg
// DO NOT EDIT!


#ifndef R3LIVEGPU_MESSAGE_STAMPEDQUATERNION_H
#define R3LIVEGPU_MESSAGE_STAMPEDQUATERNION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace r3liveGPU
{
template <class ContainerAllocator>
struct StampedQuaternion_
{
  typedef StampedQuaternion_<ContainerAllocator> Type;

  StampedQuaternion_()
    : header()
    , geoQuat()  {
    }
  StampedQuaternion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , geoQuat(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _geoQuat_type;
  _geoQuat_type geoQuat;





  typedef boost::shared_ptr< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> const> ConstPtr;

}; // struct StampedQuaternion_

typedef ::r3liveGPU::StampedQuaternion_<std::allocator<void> > StampedQuaternion;

typedef boost::shared_ptr< ::r3liveGPU::StampedQuaternion > StampedQuaternionPtr;
typedef boost::shared_ptr< ::r3liveGPU::StampedQuaternion const> StampedQuaternionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r3liveGPU::StampedQuaternion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::r3liveGPU::StampedQuaternion_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedQuaternion_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.geoQuat == rhs.geoQuat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::r3liveGPU::StampedQuaternion_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedQuaternion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace r3liveGPU

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90a2df2d0b1ff055b3959b6ad0eb308e";
  }

  static const char* value(const ::r3liveGPU::StampedQuaternion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90a2df2d0b1ff055ULL;
  static const uint64_t static_value2 = 0xb3959b6ad0eb308eULL;
};

template<class ContainerAllocator>
struct DataType< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r3liveGPU/StampedQuaternion";
  }

  static const char* value(const ::r3liveGPU::StampedQuaternion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StampedQuaternion.msg\n"
"\n"
"std_msgs/Header header\n"
"geometry_msgs/Quaternion geoQuat\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::r3liveGPU::StampedQuaternion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.geoQuat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StampedQuaternion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r3liveGPU::StampedQuaternion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r3liveGPU::StampedQuaternion_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "geoQuat: ";
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.geoQuat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R3LIVEGPU_MESSAGE_STAMPEDQUATERNION_H
