// Generated by gencpp from file r3liveGPU/StampedFloat64MultiArray.msg
// DO NOT EDIT!


#ifndef R3LIVEGPU_MESSAGE_STAMPEDFLOAT64MULTIARRAY_H
#define R3LIVEGPU_MESSAGE_STAMPEDFLOAT64MULTIARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64MultiArray.h>

namespace r3liveGPU
{
template <class ContainerAllocator>
struct StampedFloat64MultiArray_
{
  typedef StampedFloat64MultiArray_<ContainerAllocator> Type;

  StampedFloat64MultiArray_()
    : header()
    , data()  {
    }
  StampedFloat64MultiArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> const> ConstPtr;

}; // struct StampedFloat64MultiArray_

typedef ::r3liveGPU::StampedFloat64MultiArray_<std::allocator<void> > StampedFloat64MultiArray;

typedef boost::shared_ptr< ::r3liveGPU::StampedFloat64MultiArray > StampedFloat64MultiArrayPtr;
typedef boost::shared_ptr< ::r3liveGPU::StampedFloat64MultiArray const> StampedFloat64MultiArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator1> & lhs, const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace r3liveGPU

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08ae914b4d631bd1e789325b2f44c794";
  }

  static const char* value(const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08ae914b4d631bd1ULL;
  static const uint64_t static_value2 = 0xe789325b2f44c794ULL;
};

template<class ContainerAllocator>
struct DataType< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "r3liveGPU/StampedFloat64MultiArray";
  }

  static const char* value(const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# StampedFloat64MultiArray.msg\n"
"\n"
"std_msgs/Header header\n"
"std_msgs/Float64MultiArray data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StampedFloat64MultiArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::r3liveGPU::StampedFloat64MultiArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "data: ";
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // R3LIVEGPU_MESSAGE_STAMPEDFLOAT64MULTIARRAY_H
